# Generated by Django 6.0 on 2026-01-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweet_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
